version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -fsSL https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Building Terraform"
      - terraform init
      - terraform validate
      - terraform plan
