name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name NomeDaSuaStack \
            --template-file seu-template.yaml \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              GitHubRepository=https://github.com/RuanGalvao/ECSSG \
              GitHubBranch=main \
              GitHubToken= ${{ secrets.GITHUB_TOKEN }} \
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

